### PR TITLE
Added me

### PR DESCRIPTION
**Pull request by ar1a**

### CODE REVIEW

**Comment by SwadicalRag** [comment]
`glua.team.addFriend("76561198199062669","aria");`
or no

**Comment by ar1a** [comment]
why cant i be a member? :(

**Comment by SwadicalRag** [comment]
that requires more than one (1) one line CAC bypass*

\* - a line of valid Lua code less than 50 characters long that will allow you to load any lua code in the client state without being detected by CAC

**Comment by ar1a** [comment]
`function runcode(string) dostring(string) end
`
just run it in the menu state

**Pull request merged**
