### PR TITLE
Changed some absolute links to relative links

### PR DESCRIPTION
**Pull request by Shigbeard**
It made testing changes in my test environment impossible.

### CODE REVIEW

**Comment by SwadicalRag** [comment]
does the current use of absolute links break your page? if not, I don't see why we need to make the move to relative links

**Comment by Shigbeard** [comment]
It breaks my test environment, and I don't want to have to make them relative links just to test any change i happen to make. You should be using relative links anyway unless linking to an absolute resource hosted externally.

**Comment by Shigbeard** [comment]
To show you what I mean, here are some Screenshots.
Before relative links: 

After relative links:

**Comment by Shigbeard** [comment]
And yes, that's the same if I put it on ndlee.com

**Comment by SwadicalRag** [comment]
file:// isn't the same as http://

**Comment by Shigbeard** [comment]
Please read the comment above. I told you it's the same on ndlee.com, 
which is hosted with a shared hosting plan with hostgator.

**Comment by SwadicalRag** [comment]
i don't like it but i'll hit the merge button :-1:

**Pull request merged**
