### PR TITLE
Removed bigservermen link (rip site)

### PR DESCRIPTION
**Pull request by mcd1992**
Top secret promoted mcd1992 to cool dudes
Fixed indentation for two friends of glua

### CODE REVIEW

**Comment by SwadicalRag** [comment]
F

**Comment by SwadicalRag** [comment]
fuck it, i am too tired to patch out the cool dudes thing

the site is going to be rewritten to have everyone displayed equally soon

all flaming will be redirected to @mcd1992

**Comment by ThatLing** [comment]
soon™

**Comment by SwadicalRag** [comment]
after securegmod @ThatLing

**Comment by mcd1992** [comment]
Now cake is the meat in the glua sandwich

**Pull request merged**
