### PR TITLE
can i be a team glua member of honor

### PR DESCRIPTION
**Pull request by aStonePenguin**
you should merge this

### CODE REVIEW

**Comment by SwadicalRag** [comment]
`addFriend` or bust

```
addMember requires more than one (1) one line CAC bypass*

* - a line of valid Lua code less than 50 characters long that will allow you to load any lua code in the client state without being detected by CAC
```

**Comment by NotSoSuper** [comment]
rip

**Comment by aStonedPenguin** [comment]
CAC = nil

**Comment by 60percentCaffeine** [comment]
lol

**Pull request closed without merging**
