### PR TITLE
today i bypassed aletheia, potassium and meep antiscript

### PR DESCRIPTION
**Pull request by marcogravbrot**
can i be in on the big memes please

### CODE REVIEW

**Comment by marcogravbrot** [comment]
i also de-obfsucated casesium obfsucation

**Comment by NotSoSuper** [comment]
sorry sir but you must bypass CAC, not those peasant anticheats.

**Comment by marcogravbrot** [comment]
but i bypassed cac last summer!

**Comment by SwadicalRag** [comment]
wtf is happening @meepdarknessmeep

**Pull request closed without merging**
