### PR TITLE
moving down non-COOL kids

### PR DESCRIPTION
**Pull request by NotSoSuper**

### CODE REVIEW

**Comment by Kefta** [comment]
Thisisaviolationonmyrights

**Comment by Kefta** [comment]
Sorry,spacebar
is
broken

**Comment by NotSoSuper** [comment]
noitisnot

**Comment by NotSoSuper** [comment]
hahafaggot

**Comment by SwadicalRag** [comment]
no

**Comment by SwadicalRag** [comment]
i think i should make everything random

**Pull request closed without merging**
